# webservers 

services:
  web_apache:
    image: tomcat:latest
    container_name: tomcat
    ports:
      - 8888:8080

  web_nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8889:80

  web_httpd:
    image: httpd:latest
    container_name: httpd
    ports: 
      - 8890:80