services:
  web_apache:
    image: tomcat
    container_name: tomcat
    ports:
      - 8888:8080


  attacker_slowloris:
    build: ./ddos/Slowloris/slowloris/ 
    container_name: slowloris
    
  # wireshark:
  #   image: lscr.io/linuxserver/wireshark
  #   container_name: wireshark
  #   restart: unless-stopped