# webservers 

services:
  web_apache:
    image: tomcat:latest
    container_name: tomcat
    stdin_open: true
    tty: true
    ports:
      - 8888:8080

  # web_nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - 8889:80
  #   stdin_open: true
  #   tty: true

  # web_httpd:
  #   image: httpd:latest
  #   container_name: httpd
  #   ports: 
  #     - 8890:80

  # target:
  #     image: vulnerables/web-dvwa
  #     ports:
  #       - 80:80
  
  # target:
  #   build: builds/webservers
  #   ports:
  #     - 80:1313
  #   stdin_open: true
  #   tty: true

# wireshark
  # wireshark:
  #   build: builds/wireshark
  #   stdin_open: true
  #   tty: true

# attackers

  # slowloris:
  #   build: builds/slowloris
  #   deploy:
  #     replicas: 1
  #   stdin_open: true
  #   tty: true

  # hulk:
  #   build: builds/hulk
  #   deploy:
  #     replicas: $REPLICAS
  #   stdin_open: true
  #   tty: true

  # mhddos:
  #   build: builds/MHDDoS
  #   deploy:
  #     replicas: $REPLICAS
  #   stdin_open: true
  #   tty: true

  # goldeneye:
  #   build: builds/goldeneye
  #   deploy:
  #     replicas: $REPLICAS
  #   stdin_open: true
  #   tty: true
  
  hping3:
    build: builds/hping
    stdin_open: true
    tty: true
    
